telegram:
    api_id: 0
    api_hash: https://my.telegram.org

config:
    # This is the prefix used for commands (dot is most common)
    prefixes:
        - .
    sessions: 
      - yourusername
    # If you are an operator, this is required. You will need to
    # be promoted to an agent to use this feature.
    spb_token: https://t.me/SpamProtectionBot
